// Generated by CoffeeScript 1.7.1
(function() {
  var fizzbuzz, test_fifteen_gives_fizzbuzz, test_five_gives_buzz, test_one_gives_one, test_six_gives_fizz, test_three_gives_fizz, tests;

  test_one_gives_one = function() {
    return assertEquals(1, fizzbuzz(1));
  };

  test_three_gives_fizz = function() {
    return assertEquals("fizz", fizzbuzz(3));
  };

  test_six_gives_fizz = function() {
    return assertEquals("fizz", fizzbuzz(6));
  };

  test_five_gives_buzz = function() {
    return assertEquals("buzz", fizzbuzz(5));
  };

  test_fifteen_gives_fizzbuzz = function() {
    return assertEquals("fizzbuzz", fizzbuzz(15));
  };

  tests = {
    "test one is one": test_one_gives_one,
    "test three gives fizz": test_three_gives_fizz,
    "test six gives fizz": test_six_gives_fizz,
    "test five gives buzz": test_five_gives_buzz,
    "test fifteen gives fizzbuzz": test_fifteen_gives_fizzbuzz
  };

  fizzbuzz = function(n) {
    var out;
    out = "";
    if (n % 3 === 0) {
      out += "fizz";
    }
    if (n % 5 === 0) {
      out += "buzz";
    }
    if (out === "") {
      out = n;
    }
    return out;
  };

  TestCase("tests for fizzbuzz kata", tests);

}).call(this);
